### ISSUE TITLE
Details button too large?

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools-list#19] opened 2019-10-14 12:57 UTC
It seems a trifle too large (for me) and I feel it takes away from the actual content.

**Comment by slhenry** [comment] 2019-10-16 03:36
strong +1 from me

I don't like it as a button at all. I think it should be more of an expand-collapse looking control -- e.g., +/- or twistie >

**Comment by hidde** [comment] 2019-11-14 16:05
Apologies, @vmmiller  and @slhenry , I somehow missed this issue.

I just updated the details button to address https://github.com/w3c/wai-authoring-tools/issues/64, it now looks (and is) a standard WAI expand/collapse.

Please let me know if this addresses your issue!

**Comment by slhenry** [comment] 2019-11-14 16:32
+1 to the [+]

-1 to it being larger font than the surrounding text

-1 (I think) to it being a heading (probably could change my mind on that easily enough :-)

**Comment by yatil** [comment] 2019-11-14 16:35
LGTM

**Comment by vmmiller** [comment] 2019-11-14 16:35
+1 to the "+  Details"

**Comment by hidde** [comment] 2019-11-14 16:58
@slhenry [The example](https://wai-website-theme.netlify.com/components/excol/single) for ex/col has a heading, I am not sure what the context of that is but copied it. 

Wil decrease font size, it looks better.

**Comment by hidde** [comment] 2019-11-14 17:04
Closing this issue, thanks all!

**Comment by slhenry** [comment] 2019-11-14 19:08
Even though the ex/col example is a heading, you do not have to make it a heading.

Maybe it makes sense structurally for it to be a heading, maybe not? Please consider and provide brief justification for whichever way you suggest. :-)

**Comment by yatil** [comment] 2019-11-15 11:05
I reopened the issue so it does not get overlooked. Please do not comment and not reopen issues (unless an answer/addressing the issue is optional).

**Comment by hidde** [comment] 2019-11-18 13:01
@yatil thanks

@slhenry I think it structurally makes sense for it to be a heading, it has the correct level and believe it would be a useful thing to navigate to for folks who want to use headings shortcuts in their assistive tech. I also double checked that is allowed per spec for `summary` to contain a heading, and yes, [it is](https://html.spec.whatwg.org/dev/interactive-elements.html#the-summary-element).

Please let me know if that justification works for you.

**Comment by hidde** [comment] 2019-11-20 20:57
@slhenry could you please indicate if you can agree with this justification? I'd like to close this issue if we can, and believe it to be resolved.

**Closed** 2022-12-10 17:02 UTC
Labels: waiting for input (unresolved)
